services:
  - type: web
    name: financial-tracker
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: your_database_host
      - key: DB_USER
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
      - key: DB_NAME
        value: financetracker